"""Backend info: fast, no heavy imports."""

# BackendInformation imported lazily in info() to avoid circular import when
# skimage.util is loaded (util modules use @dispatchable which may call all_backends()).
SUPPORTED_FUNCTIONS = [
    "skimage.metrics:mean_squared_error",
    "skimage.metrics:normalized_root_mse",
    "skimage.metrics:peak_signal_noise_ratio",
    "skimage.metrics:structural_similarity",
    "skimage.metrics:normalized_mutual_information",
    "skimage.transform:resize",
    "skimage.transform:rescale",
    "skimage.transform:rotate",
    "skimage.transform:warp",
    "skimage.transform:resize_local_mean",
    "skimage.transform:downscale_local_mean",
    "skimage.transform:integral_image",
    "skimage.transform:integrate",
    "skimage.transform:pyramid_reduce",
    "skimage.transform:pyramid_expand",
    "skimage.transform:swirl",
    "skimage.transform:warp_polar",
    "skimage.filters:gaussian",
    "skimage.filters:sobel",
    "skimage.filters:threshold_otsu",
    "skimage.filters:threshold_li",
    "skimage.filters:threshold_yen",
    "skimage.filters:threshold_isodata",
    "skimage.filters:difference_of_gaussians",
    "skimage.filters:prewitt",
    "skimage.filters:scharr",
    "skimage.filters:median",
    "skimage.filters:laplace",
    "skimage.filters:roberts",
    "skimage.filters:unsharp_mask",
    "skimage.feature:canny",
    "skimage.feature:peak_local_max",
    "skimage.feature:match_template",
    "skimage.exposure:equalize_hist",
    "skimage.exposure:equalize_adapthist",
    "skimage.exposure:match_histograms",
    "skimage.exposure:rescale_intensity",
    "skimage.exposure:adjust_gamma",
    "skimage.morphology:remove_small_objects",
    "skimage.morphology:remove_small_holes",
    "skimage.morphology:erosion",
    "skimage.morphology:dilation",
    "skimage.morphology:opening",
    "skimage.morphology:closing",
    "skimage.morphology:white_tophat",
    "skimage.morphology:black_tophat",
    "skimage.segmentation:clear_border",
    "skimage.segmentation:expand_labels",
    "skimage.segmentation:find_boundaries",
    "skimage.segmentation:join_segmentations",
    "skimage.segmentation:relabel_sequential",
    "skimage.segmentation:mark_boundaries",
    "skimage.measure:label",
    "skimage.util:invert",
    "skimage.util:compare_images",
    "skimage.util:montage",
    "skimage.util:crop",
    "skimage.util:random_noise",
    "skimage.util:view_as_blocks",
    "skimage.util:view_as_windows",
    "skimage.color:rgb2gray",
    "skimage.color:gray2rgb",
    "skimage.color:label2rgb",
    "skimage.color:rgb2hsv",
    "skimage.color:hsv2rgb",
    "skimage.color:rgb2lab",
    "skimage.color:lab2rgb",
    "skimage.restoration:denoise_tv_chambolle",
    "skimage.restoration:richardson_lucy",
]


def info():
    """Return backend metadata. Must be fast; avoid importing cucim/cupy here."""
    from skimage.util._backends import BackendInformation

    return BackendInformation(SUPPORTED_FUNCTIONS)
